services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      - MYSQL_DATABASE=emp_demo
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
